setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          filters:
            tags:
              only: /.*/
          pre-steps:
            - run:
                command: |
                  if [[ -n "${CIRCLE_PULL_REQUEST##*/}" && ${CIRCLE_BRANCH} =~ "pull/" ]]
                  then
                    IS_PR=true
                  else
                    IS_PR=false
                  fi
                  echo '{ "is_pr": '$IS_PR' }' >> /home/circleci/params.json
