name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Coverage
    runs-on: ${{ matrix.os }}
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: he0119/setup-python@v0.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install prerequisites
        run: poetry install

      - name: Run Pytest
        run: poetry run pytest --cov-report xml --cov=./src/plugins/nonebot_bison -k 'not compare and not render'

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON_VERSION

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    concurrency:
      group: build-frontend-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Build Frontend
        run: |
          cd ./admin-frontend
          yarn install
          yarn build

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ${{ github.workspace }}/admin-frontend/build/
